blank_issues_enabled: false
contact_links:
- name: Troubleshooting, etc.
  url: https://github.com/aperloff/WDTSscraper/discussions
  about: Use 'Discussions' to request assistance, ask questions, etc.